# Generated by Django 4.2.28 on 2026-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paciente_apellido_materno'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='child_pugh',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Child-Pugh (CP)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='puntaje_flicker',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Puntaje Flicker'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='puntaje_phes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Puntaje PHES'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tiene_tx',
            field=models.BooleanField(default=False, verbose_name='Tiene Tx'),
        ),
    ]
