# Generated by Django 4.2.30 on 2026-04-16 18:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grupo_admin_proyectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopaciente',
            name='archivo',
            field=models.FileField(upload_to=core.models.video_paciente_upload_to),
        ),
    ]
